version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3333:3333"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - NETWORK=docker
    depends_on:
      - server

