name: CI Providers Task

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build server Docker image
        run: docker build -t server-image .
        
      - name: Build client Docker image
        run: docker build -t client-image .
        
      - name: Run server container
        run: |
          docker run -d --name server-container server-image
          sleep 5
          
      - name: Run client container
        run: |
          docker run -d --name client-container client-image
          sleep 5
          
      - name: Check server logs
        run: docker logs server-container
        
      - name: Check client logs
        run: docker logs client-container